services:
  blaze:
    image: ghcr.io/samply/blaze:1.0.4@sha256:43adac716f62d8535615b68a63ce91d288470ad1e39a96453771ac11eb6d5635
    environment:
      JAVA_TOOL_OPTIONS: "-Xmx16g"
      BASE_URL: "http://blaze:8080"
    volumes:
      - "blaze-data:/app/data"
    ports:
      - "127.0.0.1:8083:8080"

  fhir-to-server:
    image: ghcr.io/miracum/kafka-fhir-to-server:v3.0.3@sha256:77f0a61e91143a13ba02d47add8e73e130b8d0308e55132598f2880e4f221ad9
    restart: unless-stopped
    cap_drop:
      - ALL
    privileged: false
    ipc: none
    security_opt:
      - "no-new-privileges:true"
    environment:
      SECURITY_PROTOCOL: PLAINTEXT
      BOOTSTRAP_SERVERS: kafka:9092
      JAVA_TOOL_OPTIONS: "-XX:MaxRAMPercentage=75"
      FHIR_URL: http://blaze:8080/fhir
      # TODO: change if pseudonymization is enabled
      TOPIC: fhir.obds.MedicationStatement,fhir.obds.Condition,fhir.obds.Observation,fhir.obds.Procedure,fhir.obds.Patient

volumes:
  blaze-data: {}
